---
- name: Installation of Tomcat 10 on Ubuntu 20.04
  hosts: localhost
  become: yes
  tasks:
    - name: Create a group Tomcat
      group:
        name: tomcat
        state: present
    - name: Create an user Tomcat
      user:
        name: tomcat
        create_home: yes
        home: /opt/tomcat
        group: tomcat
        shell: /bin/false
        state: present
    - name: Update packages for Ubuntu
      apt:
        update_cache: yes
    - name: Installing Java
      package:
        name: openjdk-11-jdk
        state: present
    - name: Downloading the archive of Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
        dest: /tmp
    - name: Extracting the archive file
      unarchive:
        src: /tmp/apache-tomcat-10.0.27.tar.gz
        dest: /opt/tomcat
        remote_src: yes
    - name: Granting Tomcat ownership over the extracted installation
      command: "chown -R tomcat:tomcat /opt/tomcat/apache-tomcat-10.0.27/"
    - name: Granting Tomcat mode over the extracted installation
      command: "sudo chmod -R u+x /opt/tomcat/apache-tomcat-10.0.27/bin"
    - name: Copying the users file
      ansible.builtin.copy:
        src: tomcat-users.xml
        dest: /opt/tomcat/apache-tomcat-10.0.27/conf/tomcat-users.xml
        owner: tomcat
        group: tomcat
    - name: Copying the context file to manager
      ansible.builtin.copy:
        src: context.xml
        dest: /opt/tomcat/apache-tomcat-10.0.27/webapps/manager/META-INF/context.xml
        owner: tomcat
        group: tomcat
    - name: Copying the context file to host manager
      ansible.builtin.copy:
        src: context.xml
        dest: /opt/tomcat/apache-tomcat-10.0.27/webapps/host-manager/META-INF/context.xml
        owner: tomcat
        group: tomcat
    - name: Adding Java path to the tomcat.service
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
        owner: tomcat
        group: tomcat
    - name: Reload & Start tomcat service
      ansible.builtin.systemd:
        name: tomcat.service
        daemon_reload: yes
        state: started
        enabled: yes        