---
- name: installation apache & php server on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
    
    - name: Installing Packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - mysql-server
        - php 
        - libapache2-mod-php 
        - php-mysql
        - python3-pymysql

    - name: install php
      ansible.builtin.apt:
        name: php8.1-cli
        update_cache: yes
        state: present 

    - name: copy the info.php file
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
        
        
    